### ISSUE TITLE
Missing scene files

### ISSUE THREAD

**Issue by korzen** [surgical-vision/FetalUltrasoundSimulator-Unity#1]
Hi Chiara,

thanks a lot for sharing your work. However, it seems that the demo scenes are missing from the repository.

Thanks in advance for fixing this!

**Comment by pranavajy** [comment]
Yeah , please upload the demo scene files .

**Comment by chiaradivece** [comment]
I'll upload one as soon as possible. In the meantime, you can easily create your scene. Once you open it, you need to go to Volume Rendering > Load dataset > Load dicom, and then once the file explorer opens, you go to DataFiles > folder > Select the folder (or upload your DICOM series). Then, you can choose if you want to downscale the dataset. You can then play with the transfer function or add slicing planes.

**Comment by chiaradivece** [comment]
Added sample scenes for annotations and plane acquisitions
